# Note: These are default parameters from the documentation. Will need to be fine tuned

# Team 1: Person Detection Parameters
person_detector_node:
  ros__parameters:
    model_path: "yolov11s.pt"
    confidence_threshold: 0.5
    green_hue_min: 50
    green_hue_max: 90
    green_sat_min: 100
    green_val_min: 100
    min_green_percentage: 0.3

# Team 2: Depth Estimation Parameters
depth_estimator_node:
  ros__parameters:
    min_depth: 0.3
    max_depth: 5.0
    smoothing_factor: 0.7
    sample_ratio: 0.5

# Team 3: Follow Controller Parameters
follow_controller_node:
  ros__parameters:
    target_distance: 0.914
    k_p_distance: 0.3
    k_p_angle: 1.0
    distance_dead_zone: 0.1
    angle_dead_zone: 0.1
    max_linear_speed: 0.3
    max_angular_speed: 0.5
    emergency_stop_distance: 0.4
    target_loss_timeout: 2.0
    min_confidence: 0.5