amcl:
  ros__parameters:
    use_sim_time: true

    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    # Frames
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    scan_topic: "scan"

    map_subscribe_transient_local: true


    # Particle Filter
    min_particles: 500
    max_particles: 2000
    pf_err: 0.05
    pf_z: 0.99

    # Odometry Noise Parameters (higher values for skid-steer)
    alpha1: 0.8   # Rotational noise from rotation
    alpha2: 0.4   # Rotational noise from translation
    alpha3: 0.8   # Translational noise from translation
    alpha4: 0.4   # Translational noise from rotation
    alpha5: 0.2   # Strafe noise (not used much for differential/skid-steer)

    # Laser Model
    laser_model_type: "likelihood_field"
    laser_max_range: 30.0   # Match lidar specs
    laser_min_range: 0.1
    max_beams: 180
    sigma_hit: 0.2
    z_hit: 0.5
    z_rand: 0.5

    # Update thresholds (when to resample)
    update_min_d: 0.25   # meters
    update_min_a: 0.2    # radians (~11°)

    # Transform publishing
    tf_broadcast: true

    # Initial pose parameters (so AMCL can start without manual intervention)
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    initial_pose_covariance_x: 0.25
    initial_pose_covariance_y: 0.25
    initial_pose_covariance_yaw: 0.06853892326654787

    # Recovery behavior for kidnapped-robot scenarios
    always_reset_initial_pose: false
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1

    scan_topic_qos_override:
      reliability: "best_effort"
      durability: "volatile"
