# RoboSense LiDAR to LaserScan Converter - Z-Slice Mode Configuration
#
# Alternative configuration using Z-slice filtering instead of ring extraction.
# This mode extracts all points within a specific height range.

rslidar_to_laserscan_node:
  ros__parameters:
    # Topics
    input_topic: "/rslidar_points"
    output_topic: "/scan"
    frame_id: "laser_link"

    # Use Z-slice filtering mode
    conversion_mode: "z_slice"

    # Z-Slice Parameters
    # Extract points within this height range relative to the sensor
    z_min: -0.05    # 5cm below sensor
    z_max: 0.05     # 5cm above sensor

    # LaserScan Output Parameters
    angle_min: -3.141592653589793     # -π radians
    angle_max: 3.141592653589793      # +π radians
    angle_increment: 0.003490658503988659  # ~0.2° (1800 points per revolution)
    range_min: 0.1
    range_max: 30.0
    scan_time: 0.1