# Global Costmap Parameters
global_costmap:
  global_costmap:
    ros__parameters:
      # Basic configuration
      update_frequency: 1.0 # Update 1 Hz (static environment changes slowly)
      publish_frequency: 1.0 # Publish for RViz visualization
      global_frame: map # Use map frame from Team 1
      robot_base_frame: base_link
      use_sim_time: true 

      # Costmap will auto-size to match the map from Team 1
      resolution: 0.05 # 5cm grid cells
      track_unknown_space: false # Don't worry about unexplored areas
      use_maximum: false # Use standard cost blending

      # Scout Mini footprint
      footprint: "[[-0.356, -0.340], [0.356, -0.340], [0.356, 0.340], [-0.356, 0.340]]"

      # Layer plugins (ORDER MATTERS - processed in sequence)
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      # Static layer - incorporates Team 1's pre-built map
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true # Reliable map subscription
        enabled: true
        subscribe_to_updates: true # Listen for map changes
        transform_tolerance: 1.0

      # Obstacle layer - processes real-time LiDAR data from /scan
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan # Data source name
        footprint_clearing_enabled: true # Clear obstacles under robot
        max_obstacle_height: 2.0 # Ignore ceiling (Scout Mini is 0.285m)
        combination_method: 1 # Use maximum cost method

        # Configure the 'scan' observation source
        scan:
          topic: /scan # From rslidar_laserscan_converter
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: true # Clear previously detected obstacles
          marking: true # Mark new obstacles
          data_type: "LaserScan"
          min_obstacle_height: 0.0 # Ground level
          max_obstacle_height: 2.0 # Below ceiling

      # Inflation layer - creates safety buffer around obstacles
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.55 
        cost_scaling_factor: 10.0 
        inflate_unknown: false 
        inflate_around_unknown: true  