# Planner Server Parameters

planner_server:
  ros__parameters:
    # Basic planner configuration
    expected_planner_frequency: 20.0 # Plan up to 20 Hz when needed
    planner_plugins: ["GridBased"] # Plugin name for configuration
    use_sim_time: true  

    # Smac Hybrid-A* planner (RECOMMENDED for Scout Mini)
    GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid"

      # Costmap processing
      downsample_costmap: false # Use full resolution (important for accuracy)
      downsampling_factor: 1 # No downsampling

      # Planning parameters
      tolerance: 0.25 # Goal tolerance (25cm is reasonable)
      allow_unknown: true # Can plan through unknown areas if needed
      max_planning_time: 5.0 # Give up after 5 seconds
      max_iterations: 1000000 # Maximum search iterations
      max_on_approach_iterations: 1000 

      # Motion model for Scout Mini's skid-steer constraints
      motion_model_for_search: "DUBIN" # Dubin's car (non-holonomic)
      angle_quantization_bins: 72 # 5-degree angle resolution (360/72=5°)

      # Analytic expansion (tries direct path to goal when close)
      analytic_expansion_ratio: 3.5 # Try direct path when within 3.5× heuristic distance
      analytic_expansion_max_length: 3.0 # Maximum direct path length (meters)
      analytic_expansion_max_cost: 200.0 
      analytic_expansion_max_cost_override: false 

      # Vehicle-specific constraints
      minimum_turning_radius: 0.40 # Scout Mini's minimum turn radius

      # Path quality penalties (tuned for Scout Mini)
      reverse_penalty: 2.0 # Discourage backing up
      change_penalty: 0.0 # No penalty for direction changes (allows flexibility)
      non_straight_penalty: 1.2 # Prefer straight paths when possible
      cost_penalty: 2.0 # Avoid high-cost (near obstacle) areas
      retrospective_penalty: 0.015 # Discourage backtracking in search

      # Performance settings
      cache_obstacle_heuristic: false # Disable for dynamic environments
      lookup_table_size: 20.0 # Lookup table size in meters
      smooth_path: true # Post-process path for smoothness
      
      # Additional parameters for completeness
      debug_visualizations: false 
      use_quadratic_cost_penalty: false 
      downsample_obstacle_heuristic: true 
      allow_primitive_interpolation: false 
      coarse_search_resolution: 4 
      goal_heading_mode: "DEFAULT" 

      # Path smoother configuration
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["simple_smoother"]

    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true