amcl:
  ros__parameters:
    use_sim_time: false  
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

    # Scout Mini skid-steer motion model - higher values for wheel slip
    alpha1: 0.3  # Rotation noise from rotation
    alpha2: 0.3  # Rotation noise from translation
    alpha3: 0.3  # Translation noise from translation
    alpha4: 0.3  # Translation noise from rotation

    # Particle filter configuration
    max_particles: 2000  # Maximum particles for localization
    min_particles: 500   # Minimum particles to maintain
    pf_err: 0.05         # Particle filter error threshold
    pf_z: 0.99           # Particle filter Z-value

    # Update thresholds (how much robot must move before updating)
    update_min_d: 0.25   # Minimum translation (meters)
    update_min_a: 0.2    # Minimum rotation (radians)
    resample_interval: 1 # Resample every update

    # Transform publishing 
    tf_broadcast: true   # Publish map->odom transform
    transform_tolerance: 1.0  # Transform timeout (seconds)

    # Initial pose (set to false, will use 2D Pose Estimate in RViz)
    set_initial_pose: false
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    initial_cov:
      x: 0.25    # Initial pose covariance
      y: 0.25
      yaw: 0.1

    # Laser model for RoboSense LiDAR
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 2.0  # Maximum distance to consider obstacles
    laser_max_range: 15.0            # Maximum range of laser (meters)
    laser_min_range: 0.1             # Minimum range of laser (meters)
    max_beams: 60                    # Number of beams to use (reduce for performance)
    z_hit: 0.5                       # Weight for correct measurements
    z_short: 0.05                    # Weight for short measurements
    z_max: 0.05                      # Weight for max range measurements
    z_rand: 0.5                      # Weight for random measurements
    sigma_hit: 0.2                   # Std dev of hit distribution

    # Scan topic from rslidar_laserscan_converter
    scan_topic: scan
