# Local Costmap Parameters  

local_costmap:
  local_costmap:
    ros__parameters:
      # Rolling window configuration (follows robot with fixed size)
      update_frequency: 5.0 # Update 5 Hz for dynamic obstacles
      publish_frequency: 2.0 # Publish for visualization
      global_frame: odom # Use odom frame (local planning)
      robot_base_frame: base_link
      use_sim_time: true  

      # Rolling window size (3m x 3m around robot)
      rolling_window: true
      width: 3 # 3 meters wide
      height: 3 # 3 meters tall
      resolution: 0.05 # Same resolution as global

      # Scout Mini footprint
      footprint: "[[-0.356, -0.340], [0.356, -0.340], [0.356, 0.340], [-0.356, 0.340]]"

      # Local costmap layers (NO static layer - only dynamic obstacles)
      plugins: ["obstacle_layer", "inflation_layer"]

      # Obstacle layer (same config as global but higher update rate)
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        combination_method: 1

        scan:
          topic: /scan
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          expected_update_rate: 0.0 # No timeout (depends on LiDAR)
          observation_persistence: 0.0 # Don't keep old observations
          inf_is_valid: false # Ignore infinite laser readings
          clear_after_reading: true # Clear old data after processing
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0

      # Inflation layer (matches global costmap settings)
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.55  
        cost_scaling_factor: 10.0  
        inflate_unknown: false
        inflate_around_unknown: true