#==============================================================================
# TEAM 1: AMCL and Lifecycle Management
#==============================================================================

#==============================================================================
# TEAM 2: Costmaps and Planning
#==============================================================================

#==============================================================================
# TEAM 3: Controllers and Behavior Trees
#==============================================================================
